### ISSUE TITLE
"unary operator expected" message when zgrep absent like with OpenWRT

### ISSUE THREAD

**Issue by bertofurth** [cvmiller/v6disc#3]
When running the v4disc.sh utility by itself, or when invoking it indirectly with the "-D" dual-stack option in v6disc.sh , messages similar to the one below might be generated while the utility is running on a system that does not have "zgrep" available

./v4disc.sh: line 317: [: ==: unary operator expected
./v4disc.sh: line 320: ^AD8838: command not found
./v4disc.sh: line 317: [: ==: unary operator expected
./v4disc.sh: line 320: ^0C1F9A: command not found

OpenWRT is an example of a system that does not natively have zgrep installed.

The issue appears to be purely cosmetic. The rest of the output is fine and the v4disc utility still works great.

**Comment by bertofurth** [comment]
I think this is really easy to fix just by putting double quotes around the $zgrep" on line 317 of v4disc.sh. So just change line 317 to the following...

                       if [ "$zgrep" == "" ]; then`

**Comment by cvmiller** [comment]
Thank you for pointing this out, and suggesting a fix. I have updated v4_disc.sh with your fix, as version 0.99.7.

thanks,

**Comment by bertofurth** [comment]
N.P. BTW I love your tool. Being able to find all the link local addresses and then having the manufacturer listed is an amazing way to find new devices on the lan!! Thanks very much!

**Comment by cvmiller** [comment]
Great! Glad you find it useful. Let me know if you run into any other problems.

**Comment by bertofurth** [comment]
Just wanted to let you know, this tool is amazing. I love the latest addition in the create_manuf.sh script. Well done.

**Comment by cvmiller** [comment]
> Just wanted to let you know, this tool is amazing. I love the latest addition in the create_manuf.sh script. Well done.

It is good to hear you are finding it useful. It was definitely time to update the `wireshark_oui.gz`. I considered renaming it, since the data comes directly from the IEEE rather than wireshark.org, but for backwards compatibility, I left the name the same.
